/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author DELL
 */
public class Teorema6 extends javax.swing.JFrame {

    /**
     * Creates new form Teorema6
     */
    public Teorema6() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texfactorial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        texfactorial2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        texfactorial3 = new javax.swing.JTextField();
        texfactorial4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        resultado = new javax.swing.JToggleButton();
        txt_resultado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        MENU = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel2.setText("TEOREMA 6");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/linea2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 260, 30));

        texfactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfactorialActionPerformed(evt);
            }
        });
        getContentPane().add(texfactorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/factory.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 50, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/teorema 6 formula.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/teorema 6 formula2.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 70));

        texfactorial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfactorial2ActionPerformed(evt);
            }
        });
        getContentPane().add(texfactorial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/parentesis2.jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 30, 50));

        texfactorial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfactorial3ActionPerformed(evt);
            }
        });
        getContentPane().add(texfactorial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 50, 30));

        texfactorial4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfactorial4ActionPerformed(evt);
            }
        });
        getContentPane().add(texfactorial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 50, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/parentesis derecho.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 20, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/menos.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/factory.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 50, 40));

        resultado.setBackground(new java.awt.Color(0, 51, 0));
        resultado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("RESULTADO");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, -1));

        txt_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 110, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/factory.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 50, 40));

        MENU.setBackground(new java.awt.Color(204, 204, 0));
        MENU.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        MENU.setForeground(new java.awt.Color(204, 51, 0));
        MENU.setText("MENU");
        MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENUActionPerformed(evt);
            }
        });
        getContentPane().add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, 40));

        jButton3.setBackground(new java.awt.Color(236, 234, 234));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/boton-eliminar_579710-45 png.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 100, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/calculate_equals_icon_194844.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/teorema 6.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texfactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfactorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfactorialActionPerformed

    private void texfactorial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfactorial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfactorial2ActionPerformed

    private void txt_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resultadoActionPerformed

    private void texfactorial4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfactorial4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfactorial4ActionPerformed

    private void texfactorial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfactorial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfactorial3ActionPerformed

    private void MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENUActionPerformed
        OPERACIONES T1= new OPERACIONES  ();
        T1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MENUActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
    int num = Integer.parseInt(texfactorial.getText());
        int num1 = Integer.parseInt(texfactorial2.getText());
        int num2 = Integer.parseInt(texfactorial3.getText());
        int num3 = Integer.parseInt(texfactorial4.getText());
        double fact=1;
        double mult;
        double r=1;
        double resta;
        double fact1=1;
        double resultado;
        
        
        for (int i=1; i<=num; i++){
             fact=fact*i;
        }
        for (int i=1; i<=num1; i++){
             r=r*i;
        }
        resta=(num2-num3);
        for (int j=1; j<=resta; j++){
             fact1=fact1*j;
        }
        mult=r*fact1;
        resultado=(fact/mult);
        txt_resultado.setText("" + resultado);
    }//GEN-LAST:event_resultadoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.texfactorial.setText("");
        this.texfactorial2.setText("");
        this.texfactorial3.setText("");
        this.texfactorial4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teorema6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teorema6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teorema6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teorema6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teorema6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MENU;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton resultado;
    private javax.swing.JTextField texfactorial;
    private javax.swing.JTextField texfactorial2;
    private javax.swing.JTextField texfactorial3;
    private javax.swing.JTextField texfactorial4;
    private javax.swing.JTextField txt_resultado;
    // End of variables declaration//GEN-END:variables
}
