/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author DELL
 */
public class Teorema7 extends javax.swing.JFrame {

    /**
     * Creates new form Teorema7
     */
    public Teorema7() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        suma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        suma1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        resta = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        txt_resultado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel2.setText("TEOREMA 7");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 210, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/teorema 7 formula.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 340, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/formula7.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/calculate_equals_icon_194844.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 30, -1));

        suma.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        getContentPane().add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 70, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/addition-sign_icon-icons.com_73100.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 40, 30));

        suma1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        suma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suma1ActionPerformed(evt);
            }
        });
        getContentPane().add(suma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 60, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/menos.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, 30));

        resta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 60, 30));

        jToggleButton1.setBackground(new java.awt.Color(0, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 204, 204));
        jToggleButton1.setText("RESULTADO");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 40));

        txt_resultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 190, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/menu1.jpeg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 80, 40));

        jButton3.setBackground(new java.awt.Color(236, 234, 234));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/boton-eliminar_579710-45 png.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 100, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/letter-p-symbol_icon-icons.com_57122.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/parentesis2.jpeg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/parentesis derecho.jpeg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/teorema7.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaActionPerformed

    private void suma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suma1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    double num = Double.parseDouble(suma.getText());
        double num1 = Double.parseDouble(suma1.getText());
        double num2 = Double.parseDouble(resta.getText());        
        
        double resultado;
        resultado=(num+num1)-num2;
        
        txt_resultado.setText("" + resultado);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OPERACIONES T2= new OPERACIONES  ();
        T2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.txt_resultado.setText("");
        this.suma.setText("");
        this.suma1.setText("");
        this.resta.setText("");
        this.txt_resultado.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teorema7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teorema7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teorema7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teorema7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teorema7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField resta;
    private javax.swing.JTextField suma;
    private javax.swing.JTextField suma1;
    private javax.swing.JTextField txt_resultado;
    // End of variables declaration//GEN-END:variables
}
